### PR TITLE
Made ONEP host more flexible

### PR DESCRIPTION
**Pull request by danslimmon**
I tried to leave the `InDev` functionality working in case anything uses it, but I want to be able to set my 1P host to any arbitrary thing, so I added the `OnepHost` variable.

### CODE REVIEW

**Comment by cuuboy** [comment]
Good idea, thanks!

**Comment by danslimmon** [comment]
Sweet! So will you merge it?

**Comment by danslimmon** [comment]
... @cuuboy? Will you merge this? Or do you want to make me a collaborator on the project so I can do it?

**Comment by danslimmon** [comment]
Hey, you don't work at Exosite anymore, right? Maybe you should transfer ownership of this project to me?

**Pull request merged**
